name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List Files
          run: |
            echo "My First Workflow"
            ls -lstr
            cat README.md
