name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Workflow"

        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List Files
          run: ls -lisa

        - name: Read File
          run: cat README.md
