name: ART IS COOL

on: push

jobs:
    generate_ascii:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List files
          run: ls -ltra

        - name: Execute script
          run: |
            chmod +x ./ascii-script.sh
            .github/workflows/ascii-script.sh
        
            
