name: Test script

on: push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay
        run: sudo apt install cowsay -y

      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover!!!!" >> dragon.txt

      - name: Sleep
        run: sleep 30

    test_job_2:
      runs-on: ubuntu-latest
      steps:
        - name: Sleep
          run: sleep 10

        - name: Test file exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
      runs-on: ubuntu-latest
      steps:
        - name: Read file
          run: cat dargon.txt

        - name: Deploy
          run: echo Deploying ... .. .